export const countries = [
    "Andorra",
    "Emiratos Arabes Unidos",
    "Afganistan",
    "Antigua y Barbuda",
    "Anguila",
    "Albania",
    "Armenia",
    "Angola",
    "Antartida",
    "Argentina",
    "Samoa Americana",
    "Austria",
    "Australia",
    "Aruba",
    "Islas de Åland",
    "Azerbaiyan",
    "Bosnia y Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgica",
    "Burkina Faso",
    "Bulgaria",
    "Bahrein",
    "Burundi",
    "Benin",
    "San Bartolome",
    "Islas Bermudas",
    "Brunei",
    "Bolivia",
    "Bonaire, San Eustaquio y Saba",
    "Brasil",
    "Bahamas",
    "Bhutan",
    "Isla Bouvet",
    "Botsuana",
    "Bielorrusia",
    "Belice",
    "Canada",
    "Islas Cocos (Keeling)",
    "Republica Democratica del Congo",
    "Republica Centroafricana",
    "Republica del Congo",
    "Suiza",
    "Costa de Marfil",
    "Islas Cook",
    "Chile",
    "Camerun",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curazao",
    "Isla de Navidad",
    "Chipre",
    "Republica Checa",
    "Alemania",
    "Yibuti",
    "Dinamarca",
    "Dominica",
    "Republica Dominicana",
    "Argelia",
    "Ecuador",
    "Estonia",
    "Egipto",
    "Sahara Occidental",
    "Eritrea",
    "España",
    "Etiopia",
    "Finlandia",
    "Fiyi",
    "Islas Malvinas",
    "Micronesia",
    "Islas Feroe",
    "Francia",
    "Gabon",
    "Reino Unido de Gran Bretaña e Irlanda del Norte",
    "Granada",
    "Georgia",
    "Guayana Francesa",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Groenlandia",
    "Gambia",
    "Guinea",
    "Guadalupe",
    "Guinea Ecuatorial",
    "Grecia",
    "Islas Georgias del Sur y Sandwich del Sur",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong kong",
    "Islas Heard y McDonald",
    "Honduras",
    "Croacia",
    "Haiti",
    "Hungria",
    "Indonesia",
    "Irlanda",
    "Israel",
    "Isla de Man",
    "India",
    "Territorio Britanico del Oceano indico",
    "Irak",
    "Iran",
    "Islandia",
    "Italia",
    "Jersey",
    "Jamaica",
    "Jordania",
    "Japon",
    "Kenia",
    "Kirguistan",
    "Camboya",
    "Kiribati",
    "Comoras",
    "San Cristobal y Nieves",
    "Corea del Norte",
    "Corea del Sur",
    "Kuwait",
    "Islas Caiman",
    "Kazajistan",
    "Laos",
    "Libano",
    "Santa Lucia",
    "Liechtenstein",
    "Sri lanka",
    "Liberia",
    "Lesoto",
    "Lituania",
    "Luxemburgo",
    "Letonia",
    "Libia",
    "Marruecos",
    "Monaco",
    "Moldavia",
    "Montenegro",
    "San Martin (Francia)",
    "Madagascar",
    "Islas Marshall",
    "Macedônia",
    "Mali",
    "Birmania",
    "Mongolia",
    "Macao",
    "Islas Marianas del Norte",
    "Martinica",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauricio",
    "Islas Maldivas",
    "Malawi",
    "Mexico",
    "Malasia",
    "Mozambique",
    "Namibia",
    "Nueva Caledonia",
    "Niger",
    "Isla Norfolk",
    "Nigeria",
    "Nicaragua",
    "Paises Bajos",
    "Noruega",
    "Nepal",
    "Nauru",
    "Niue",
    "Nueva Zelanda",
    "Oman",
    "Panama",
    "Peru",
    "Polinesia Francesa",
    "Papua Nueva Guinea",
    "Filipinas",
    "Pakistan",
    "Polonia",
    "San Pedro y Miquelon",
    "Islas Pitcairn",
    "Puerto Rico",
    "Palestina",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Rumania",
    "Serbia",
    "Rusia",
    "Ruanda",
    "Arabia Saudita",
    "Islas Salomon",
    "Seychelles",
    "Sudan",
    "Suecia",
    "Singapur",
    "Santa Elena",
    "Eslovenia",
    "Svalbard y Jan Mayen",
    "Eslovaquia",
    "Sierra Leona",
    "San Marino",
    "Senegal",
    "Somalia",
    "Surinam",
    "Republica de Sudan del Sur",
    "Santo Tome y Principe",
    "El Salvador",
    "Sint Maarten",
    "Siria",
    "Swazilandia",
    "Islas Turcas y Caicos",
    "Chad",
    "Territorios Australes y Antarticas Franceses",
    "Togo",
    "Tailandia",
    "Tayikistan",
    "Tokelau",
    "Timor Oriental",
    "Turkmenistan",
    "Tunez",
    "Tonga",
    "Turquia",
    "Trinidad y Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ucrania",
    "Uganda",
    "Islas Ultramarinas Menores de Estados Unidos",
    "Estados Unidos de America",
    "Uruguay",
    "Uzbekistan",
    "Ciudad del Vaticano",
    "San Vicente y las Granadinas",
    "Venezuela",
    "Islas Virgenes Britanicas",
    "Islas Virgenes de los Estados Unidos",
    "Vietnam",
    "Vanuatu",
    "Wallis y Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "Sudafrica",
    "Zambia",
    "Zimbabue",
];
